- components/Controllers/OpenVault/VaultDebtPicker/VaultDebtPicker.module.css
- components/Controllers/OpenVault/VaultDebtPicker/VaultDebtPicker.tsx
https://user-images.githubusercontent.com/7279416/216108645-f40a4065-0624-47e3-b892-61138d3b8d49.mov
> NFT-846: Debt input box enhancements

- __tests__/components/Controllers/LPPageContent.test.tsx
- components/Controllers/LPPageContent/HowToLP.tsx
- hooks/usePoolStats/usePoolStats.ts
> NFT-852: Display fee tier correctly on HowToLP

- components/Controllers/Loans/Loans.module.css
- components/Controllers/Loans/VaultHealth.tsx
> NFT-838: New vault indicator

- components/Controllers/OpenVault/VaultDebtPicker/VaultDebtPicker.module.css
- components/Controllers/OpenVault/VaultDebtPicker/VaultDebtPicker.tsx
> NFT-680: Show cost to close and maximum loan amount in borrow fieldset

- components/ContractStatus/ContractStatus.module.css
> fix: css tweaks from rinkeby

- components/Controllers/OpenVault/VaultDebtPicker/VaultDebtPicker.module.css
- components/Controllers/OpenVault/VaultDebtPicker/VaultDebtPicker.tsx
- lib/numberFormat.ts
> feat: default to 5 decimal places precision and only show cost to close when edit loan form toggled off

- __tests__/lib/controllers/index.test.ts
- components/SwapPageContent/ImpactProjection.module.css
- components/SwapPageContent/ImpactProjection.tsx
- components/SwapPageContent/SwapPageContent.module.css
- components/SwapPageContent/SwapPageContent.tsx
- lib/controllers/index.ts
demo: https://v2-interface-rosy.vercel.app/tokens/paprTrash/swap
> [NFT-740] feat: Swap Impact Projection

- components/Controllers/Charts/Charts.module.css
- components/Controllers/Charts/Charts.tsx
> [NFT-874] fix: updated chart colors

- components/Controllers/OpenVault/VaultDebtPicker/VaultDebtPicker.module.css
- components/Controllers/OpenVault/VaultDebtPicker/VaultDebtPicker.tsx
- components/YourPositions/YourPositions.tsx
> NFT-867: Audit usage of WETH <> USDC

- components/Controllers/Loans/Loans.tsx
> [NFT-869] fix: use correct totalSupply

- components/Controllers/Charts/Charts.tsx
> [NFT-876] fix: chart on mobile

- __tests__/components/ContractStatus.test.tsx
- components/ContractStatus/Common.tsx
- components/ContractStatus/ContractStatus.module.css
- components/ContractStatus/RatesNegative.tsx
- components/ContractStatus/RatesPositive.tsx
> [NFT-864] fix: contract status changes

- components/Controllers/OpenVault/VaultDebtPicker/VaultDebtPicker.tsx
- components/Controllers/TokenPerformance/Tooltips.tsx
> NFT-883: NFT value tooltip

- components/SwapPageContent/SwapPageContent.module.css
- components/SwapPageContent/SwapPageContent.tsx
> [NFT-884] fix: padding, swap fee tooltip

- components/Controllers/Collateral/Collateral.module.css
- components/Controllers/Collateral/Collateral.tsx
> NFT-843: Collateral stats

- components/Controllers/AuctionPageContent/AuctionGraph.tsx
- components/Controllers/AuctionPageContent/AuctionPageContent.tsx
> NFT-885: Update auction page to use WETH

- components/YourPositions/YourPositions.tsx
- hooks/usePaprBalance/usePaprBalance.tsx
- hooks/useTarget/useTarget.tsx
> NFT-890: Ensure performance page does not revert on wrong network

- components/Controllers/AuctionPageContent/AuctionApproveAndBuy.tsx
- hooks/useMulticallWrite/useMulticallWrite.ts
- hooks/useSafeTransferFromWrite/useSafeTransferFromWrite.ts
Wagmi now works without us having to pass overrides
> NFT-900: Remove gas overrides

- components/Controllers/OpenVault/VaultDebtPicker/VaultDebtPicker.tsx
> NFT-911: Column should read PAPR

- components/Footer/Footer.module.css
- components/Footer/Footer.tsx
- components/LandingPageContent/MainLandingPage/LandingPageContent.module.css
> [NFT-896, NFT-902] feat: updated footer

- middleware.ts
- pages/tokens/[token]/index.tsx
Just returning a bare 403 for users in "restricted territories" per our TOS.
> compliance: restrict certain territories from accessing

- components/PoolStats/PoolStats.tsx
- hooks/usePoolStats/usePoolStats.ts
> [NFT-917] feat: show TVL on pool stats

- components/Button/Button.module.css
- components/Button/GradientButtonLink.tsx
- components/LandingPageContent/MainLandingPage/LandingPageContent.module.css
- components/LandingPageContent/MainLandingPage/PaprMemeBanner.tsx
- pages/_app.tsx
Merge this when we're ready to open paprMEME up to the public
> [NFT-920, NFT-923] feat: swap over to paprMEME

- components/Controllers/Collateral/Collateral.tsx
> fix: collateral ratio calculation

- graphql/uniswap/queries/swapsByPool.graphql
| before | after |
| ----- | ----- |
| ![image](https://user-images.githubusercontent.com/9300702/218290092-705e51cb-cdfd-446b-a4f0-87d65f07dedf.png) | ![image](https://user-images.githubusercontent.com/9300702/218290085-ebdee30a-f372-48ba-8cb5-57962c790144.png)|
> [NFT-931] fix: boost swaps query

- components/Controllers/OpenVault/VaultDebtPicker/VaultDebtPicker.tsx
> NFT-927: Fix cost to close on vault debt picker

- components/Controllers/Charts/Charts.tsx
- hooks/useControllerPricesData/useControllerPricesData.ts
> fix: avoid huge outliers in charts

- components/LandingPageContent/MainLandingPage/Whitepaper.tsx
https://twitter.com/FedorLinnik/status/1625917331141427201
> fix: spelling

- components/PoolStats/PoolStats.tsx
- graphql/uniswap/fragments/allPoolProperties.graphql
- graphql/uniswap/queries/poolById.graphql
- graphql/uniswap/queries/poolByIdByBlock.graphql
- hooks/usePoolStats/usePoolStats.ts
| before | after |
| ----- | ----- |
| ![image](https://user-images.githubusercontent.com/9300702/219684433-4defc4f9-c3d0-4fbe-972e-a931c72a7a91.png) | ![image](https://user-images.githubusercontent.com/9300702/219684497-1f4bcb7f-9513-4362-afa3-2dc0db3f2d0a.png) |
> feat: bring back 24h pool data

- components/ContractStatus/Common.tsx
- components/Controllers/ApproveButtons/ApproveNFTButton.tsx
- components/Controllers/ApproveButtons/ApproveTokenButton.tsx
- components/Slider/Slider.tsx
This PR adds pirsch events for the following:
- expand/collapse on the ContractStatus details
- dragging the slider on the borrow page
- success/failure of approving NFTs/ERC20s
> [NFT-841] feat: more pirsch events

- __tests__/lib/account.test.ts
- lib/contracts.ts
While auditing our use of contract reads, found a number of contract factories we weren't using.
> chore: clean up unused code

- components/Controllers/OpenVault/VaultWriteButton.tsx
> NFT-958: New vault button texts

- components/Controllers/AuctionPageContent/AuctionGraph.tsx
- components/Controllers/AuctionPageContent/AuctionPageContent.tsx
> fix: ensure coingecko works on production and use LOWER for auction display info

- components/NFTMarquee/NFTMarquee.module.css
- components/NFTMarquee/NFTMarquee.stories.tsx
- components/NFTMarquee/NFTMarquee.tsx
- components/NFTMarquee/index.ts
- package.json
- yarn.lock
will be used in the loans update, right now only exists in a story
> feat: add NFTMarquee component

- components/SwapPageContent/SwapPageContent.tsx
https://user-images.githubusercontent.com/7279416/222211260-37292631-4b45-4659-ab7e-c1196a0c9c52.mov
> NFT-964: Fix swap impact projection not working when not using underlying

- hooks/useLatestMarketPrice/index.ts
- hooks/useLatestMarketPrice/useLatestMarketPrice.tsx
- lib/config.ts
- pages/tokens/[token]/auctions/[id].tsx
- pages/tokens/[token]/borrow.tsx
- pages/tokens/[token]/index.tsx
- pages/tokens/[token]/lp/index.tsx
- pages/tokens/[token]/swap/index.tsx
- pages/tokens/[token]/vaults/[id].tsx
Another piece of NFT-967, we're going to query for market price in more places now so we should have a single source of truth that updates periodically
> chore: provider for market price

- components/Controllers/Loans/Loans.tsx
Another small chunk of the loan table PR, aggregate loan health (e.g. avg ltv for all loans vs the max ltv) now uses the base `HealthBar` component rather than `VaultHealth` which will simplify some operations in the future
> chore: use HealthBar for aggregate loan health

- components/ApplicationProviders/ApplicationProviders.tsx
- components/Controllers/Loans/Loans.module.css
- components/Controllers/Loans/Loans.tsx
- components/Controllers/Loans/VaultHealth.tsx
- components/Controllers/Loans/VaultRow.tsx
- components/Tooltip/Tooltip.module.css
- hooks/useOracleInfo/index.ts
- lib/numberFormat.ts
- pages/tokens/[token]/test.tsx
> [NFT-967] wip: new loans table

- components/Slider/Slider.module.css
- components/Slider/Slider.stories.tsx
- components/Slider/Slider.tsx
- public/grabber-danger.svg
part of [NFT-1013]
| normal (all themes) | past threshold (all themes) |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/9300702/226942399-55189a8d-6058-43a6-868a-acfd118e145b.png) | ![image](https://user-images.githubusercontent.com/9300702/226942457-d9d97e16-35ed-4058-b2ca-b596f5b17951.png) |
> feat: indicate risk on slider

- components/Controllers/OpenVault/VaultDebtPicker/VaultDebtPicker.module.css
> NFT-948: Indent loan action summary according to designs

- components/Controllers/OpenVault/VaultDebtExplainer/VaultDebtExplainer.module.css
- components/Controllers/OpenVault/VaultDebtExplainer/VaultDebtExplainer.tsx
- components/Controllers/OpenVault/VaultDebtExplainer/index.ts
- components/Controllers/OpenVault/VaultDebtPicker/VaultDebtExplainer.tsx
- components/Controllers/OpenVault/VaultDebtPicker/VaultDebtPicker.tsx
- components/Controllers/OpenVault/VaultDebtSlider/VaultDebtSlider.tsx
- components/Tooltip/Tooltip.module.css
- components/Tooltip/Tooltip.stories.tsx
- components/Tooltip/TooltipReference.tsx
- components/Tooltip/index.ts
> [NFT-1013] feat: borrow page tooltips

- codegen/inKind.yml
- components/Controllers/Activity/Activity.tsx
- components/Controllers/BorrowPageContent/BorrowPageContent.tsx
- graphql/inKind/fragments/allActivityProperties.graphql
- graphql/inKind/queries/lpActivityByControllerAndAccount.graphql
- lib/config.ts
- lib/controllers/uniswap/index.ts
- lib/pAPRSubgraph.ts
This will all be refactored into a hook in a future PR, just wanted to merge this, along with #427 so I can combine the logic in the PRs together in the future.
> ongoing-feature: Helper methods to compute implicit swaps

- components/EligibleCollections/Collection.tsx
- components/EligibleCollections/ConnectWallet.tsx
- components/EligibleCollections/EligibleCollections.module.css
- components/EligibleCollections/EligibleCollections.tsx
- components/EligibleCollections/constants.ts
- components/EligibleCollections/index.ts
- components/LandingPageContent/MainLandingPage/LandingPageContent.tsx
- hooks/useMaxDebt/index.ts
- hooks/useMaxDebt/useMaxDebt.ts
> [NFT-991] feat: homepage collateral marquee

- components/Controllers/AuctionPageContent/AuctionPageContent.tsx
- components/Controllers/BorrowPageContent/BorrowPageContent.tsx
- components/Controllers/ControllerOverviewContent/ControllerOverviewContent.tsx
- components/YourPositions/YourPositions.module.css
- components/YourPositions/YourPositions.tsx
- hooks/useETHToUSDPrice/index.ts
- hooks/useETHToUSDPrice/useETHToUSDPrice.ts
> NFT-990: New your positions fieldset

- hooks/useCollectionTwapBidChange/useCollectionTwapBidChange.ts
- pages/api/tokens/[token]/twabs/collections/[collection].ts
> [NFT-1154] fix: hasura api route
